// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/HYY-yu/seckill.pkg/cache_v2"
	"github.com/HYY-yu/seckill.pkg/db"
	"github.com/HYY-yu/seckill.shop/proto"
	"github.com/HYY-yu/seckill.sk/internal/service/sk/api/handler"
	"github.com/HYY-yu/seckill.sk/internal/service/sk/api/repo"
	"github.com/HYY-yu/seckill.sk/internal/service/sk/api/svc"
)

// Injectors from wire.go:

// initHandlers init Handlers.
func initHandlers(d db.Repo, c cache_v2.Repo, client proto.ShopClient) (*Handlers, error) {
	skRepo := repo.NewSKRepo()
	skSvc := svc.NewSKSvc(d, c, skRepo, client)
	skHandler := handler.NewSKHandler(skSvc)
	userRepo := repo.NewUserRepo()
	userSvc := svc.NewUserSvc(d, c, userRepo)
	loginHandler := handler.NewLoginHandler(userSvc)
	orderRepo := repo.NewOrderRepo()
	orderSvc := svc.NewOrderSvc(d, c, skRepo, orderRepo, userRepo, client)
	orderHandler := handler.NewOrderHandler(orderSvc)
	handlers := NewHandlers(skHandler, loginHandler, orderHandler)
	return handlers, nil
}
