[jwt]
expireDuration = "2h"
secret = "i1ydX9RtHyuJTrw7frcu"
type = "refresh_token"
# type = "black_list"
refreshDuration = "168h"

[mysql]
[mysql.base]
connMaxLifeTime = "60s"
maxIdleConn = 60
maxOpenConn = 10
addr = "mysql-0.mysql.mysql.svc.cluster.local:3306"
name = "seckill"
pass = "root"
user = "root"

[redis]
addr = "redis.mysql.svc.cluster.local:6379"
db = "0"
maxRetries = 3
minIdleConns = 5
pass = "redis"
poolSize = 10

[log]
logPath = "./sk-shop-sk.log"
level = "debug" # DEBUG INFO WARN ERROR
stdout = true

[server]
serverName = "sk_shop_sk"
host = ":8091"
pprof = true
[server.grpc]
shopHost = ":8082"

[jaeger]
udpEndpoint = "http://tempo.kube-ops.svc.cluster.local:14268/api/traces"
stdOut = true

[elasticJobETCD]
endpoints = ["infra-etcd-cluster-0.infra-etcd-cluster.etcd.svc.cluster.local:2379"]
dialTimeout = "5s"
username = "root"
password = "123321"