[jwt]
expireDuration = 24
secret = "i1ydX9RtHyuJTrw7frcu"

[mysql]
[mysql.base]
connMaxLifeTime = 60
maxIdleConn = 60
maxOpenConn = 10
addr = "127.0.0.1:3306"
name = "seckill"
pass = "root"
user = "root"

[redis]
addr = "127.0.0.1:6379"
db = "0"
maxRetries = 3
minIdleConns = 5
pass = "redis"
poolSize = 10

[log]
logPath = "./sk-shop-sk.log"
level = "debug" # DEBUG INFO WARN ERROR
stdout = true

[server]
serverName = "sk_shop_sk"
host = ":8091"
pprof = true
[server.grpc]
shopHost = ":8082"

[jaeger]
udpEndpoint = "http://localhost:14268/api/traces"
stdOut = true

[elasticJobETCD]
endpoints = ["0.0.0.0:2379", "0.0.0.0:12379", "0.0.0.0:22379"]
dialTimeout = "5s"
username = ""
password = ""